In [3]:
import polars as pl
from pathlib import Path

In [4]:
DATA_GENERAL = Path("../data_general")
DATA_PERSONAL = Path("../data_personal/Spotify Extended Streaming History")

In [5]:
general_data_frames = []
for num in range (10) :
    general_data_frames.append(pl.read_parquet(DATA_GENERAL / f'spotify_audio_features_{num}.parquet'))

In [6]:
display(general_data_frames[0].head())

shape: (5, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ id         ┆ name       ┆ popularit ┆ null_resp ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ---        ┆ ---        ┆ y         ┆ onse      ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ str        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│            ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 2Pe9cbhOTv ┆ I dreamt   ┆ 0         ┆ 0         ┆ … ┆ 0.816     ┆ 0.737     ┆ 0.177    ┆ 0.0299  │
│ OUTDE4bl7z ┆ you died   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zl         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 0wP732NKm8 ┆ It's Death ┆ 0         ┆ 0         ┆ … ┆ 0.587     ┆ 0.782     ┆ 0.202    ┆ 0.36    │
│ XgXu78XLRW ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ oR         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 22L6EJdnjx ┆ Preliminar ┆ 0         ┆ 0         ┆ … ┆ 0.923     ┆ 0.939     ┆ 0.106    ┆ 0.0362  │
│ 8oIo7GiF9h ┆ y          ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ Le         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 3a519lgQ13 ┆ Disparage  ┆ 0         ┆ 0         ┆ … ┆ 0.78      ┆ 0.799     ┆ 0.132    ┆ 0.0634  │
│ JXNi0G73mw ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ MT         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 27yP7p2lxW ┆ Cut Down   ┆ 0         ┆ 0         ┆ … ┆ 0.843     ┆ 0.109     ┆ 0.126    ┆ 0.187   │
│ YTtnldRN8K ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zx         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [7]:
personal_data_frames = {}
for num in range (2022,2027) :
    personal_data_frames[num] = pl.read_json(
        DATA_PERSONAL / f'Streaming_History_Audio_{num}.json',
        infer_schema_length=None  
        )

In [8]:
personal_data_frames[2022] =personal_data_frames[2022].with_columns(pl.col("spotify_track_uri").str.slice(14,22))

In [9]:
check_mus_id = personal_data_frames[2022]["spotify_track_uri"][0]
print(check_mus_id)

4u7EnebtmKWzUH433cf5Qv

In [10]:
#print(len(general_data_frames))
for g in range(10):
    general_data_frames[g] = general_data_frames[g].rename({ 'id' : 'spotify_track_uri' })
print(general_data_frames[0])

shape: (25_558_893, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name       ┆ popularit ┆ null_resp ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---        ┆ y         ┆ onse      ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 2Pe9cbhOTv ┆ I dreamt   ┆ 0         ┆ 0         ┆ … ┆ 0.816     ┆ 0.737     ┆ 0.177    ┆ 0.0299  │
│ OUTDE4bl7z ┆ you died   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zl         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 0wP732NKm8 ┆ It's Death ┆ 0         ┆ 0         ┆ … ┆ 0.587     ┆ 0.782     ┆ 0.202    ┆ 0.36    │
│ XgXu78XLRW ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ oR         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 22L6EJdnjx ┆ Preliminar ┆ 0         ┆ 0         ┆ … ┆ 0.923     ┆ 0.939     ┆ 0.106    ┆ 0.0362  │
│ 8oIo7GiF9h ┆ y          ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ Le         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 3a519lgQ13 ┆ Disparage  ┆ 0         ┆ 0         ┆ … ┆ 0.78      ┆ 0.799     ┆ 0.132    ┆ 0.0634  │
│ JXNi0G73mw ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ MT         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 27yP7p2lxW ┆ Cut Down   ┆ 0         ┆ 0         ┆ … ┆ 0.843     ┆ 0.109     ┆ 0.126    ┆ 0.187   │
│ YTtnldRN8K ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zx         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …       │
│ 0SDqCqvWzQ ┆ What       ┆ 1         ┆ 0         ┆ … ┆ 0.819     ┆ 0.0       ┆ 0.076    ┆ 0.137   │
│ t870CpFV2T ┆ You're     ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ tJ         ┆ Doing To   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆ Me         ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 5gWtSuvakc ┆ Necklace   ┆ 1         ┆ 0         ┆ … ┆ 0.849     ┆ 0.000198  ┆ 0.35     ┆ 0.219   │
│ UnYy21pEzy ┆ and A      ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ uP         ┆ Stone      ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 1ol5fazT5K ┆ This       ┆ 0         ┆ 0         ┆ … ┆ 0.0432    ┆ 0.000006  ┆ 0.117    ┆ 0.156   │
│ JY4dSRSMIm ┆ Life's A   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zf         ┆ Game -     ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆ Extended … ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 6QMZLZ4ew1 ┆ AUDI       ┆ 2         ┆ 0         ┆ … ┆ 0.0238    ┆ 0.0       ┆ 0.501    ┆ 0.314   │
│ SWiCAPubal ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ ti         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 2AXkG13zpn ┆ MAZDA      ┆ 0         ┆ 0         ┆ … ┆ 0.24      ┆ 0.0168    ┆ 0.121    ┆ 0.61    │
│ 8dTddrB006 ┆ MIATA      ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ kG         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [11]:
status = False
mus_name = ''
for g in range(10):
    for url in general_data_frames[g]['spotify_track_uri']:
        if url == check_mus_id:
            status = True
            mus_name = general_data_frames[g].filter(pl.col('spotify_track_uri') == url).select(['name',])
            break
    if status :
        break

print(status, mus_name)

True shape: (1, 1)
┌─────────────────────────────────┐
│ name                            │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Bohemian Rhapsody - Remastered… │
└─────────────────────────────────┘

# NOW LET`S FIND OUT TRACK

In [12]:
song_uri = '3U0UXxBIfjUsJ8RtxoxUFn'

In [ ]:

for g in range (10):
    if song_uri in general_data_frames[g]['spotify_track_uri']:
        #print(g)
        stats = general_data_frames[g].filter(pl.col('spotify_track_uri') == song_uri)
        break

2

In [19]:
display(stats)

shape: (1, 17)
┌────────────┬──────────┬────────────┬────────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name     ┆ popularity ┆ null_respo ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---      ┆ ---        ┆ nse        ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str      ┆ i64        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆          ┆            ┆ i64        ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪══════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 3U0UXxBIfj ┆ Monolith ┆ 64         ┆ 0          ┆ … ┆ 0.000409  ┆ 0.756     ┆ 0.114    ┆ 0.799   │
│ UsJ8RtxoxU ┆          ┆            ┆            ┆   ┆           ┆           ┆          ┆         │
│ Fn         ┆          ┆            ┆            ┆   ┆           ┆           ┆          ┆         │
└────────────┴──────────┴────────────┴────────────┴───┴───────────┴───────────┴──────────┴─────────┘

# I have priority on the  energy, instrumentalness and valence

In [46]:
# Writ None in coeficients if you want to not search for this parameters
# In cof`s writre cof like 

cof_tempo = None        #       diff in BPM
cof_dance = 0.3         #       from 0 to 1
cof_energy = 0.01       #       from 0 to 1
cof_loud = None         #       diff in dB (0 dB - max loudness)
cof_speech = 0.5       #       from 0 to 1
cof_acoustic = 0.5     #       from 0 to 1
cof_instr = 0.05        #       from 0 to 1 
cof_live = 0.2         #       from 0 to 1 
cof_valence = 0.07      #       from 0 to 1 


#energy = (float(stats['energy'][0]) - 0.02 , float(stats['energy'][0]) + 0.02 )
#instr = (float(stats['instrumentalness'][0]) - 0.02 , float(stats['instrumentalness'][0]) + 0.02 )
#valence = (float(stats['valence'][0]) - 0.02 , float(stats['valence'][0]) + 0.02 )

#print(energy)

In [41]:
result = general_data_frames[2]#

In [47]:
if cof_tempo:
    ...
if cof_dance:
    state = stats['danceability']
    result = result.filter((pl.col('danceability').is_between(state*(1 - cof_dance) ,state*(1 + cof_dance) )))
if cof_energy:
    state = stats['energy']
    result = result.filter((pl.col('energy').is_between(state*(1 - cof_energy) ,state*(1 + cof_energy) )))
if cof_loud:
    ...
if cof_speech:
    state = stats['speechiness']
    result = result.filter((pl.col('speechiness').is_between(state*(1 - cof_speech) ,state*(1 + cof_speech) )))
if cof_acoustic:
    state = stats['acousticness']
    result = result.filter((pl.col('acousticness').is_between(state*(1 - cof_acoustic) ,state*(1 + cof_acoustic) )))
if cof_instr:
    state = stats['instrumentalness']
    result = result.filter((pl.col('instrumentalness').is_between(state*(1 - cof_instr) ,state*(1 + cof_instr) )))
if cof_live:
    state = stats['liveness']
    result = result.filter((pl.col('liveness').is_between(state*(1 - cof_live) ,state*(1 + cof_live) )))
if cof_valence:
    state = stats['valence']
    result = result.filter((pl.col('valence').is_between(state*(1 - cof_valence) ,state*(1 + cof_valence) )))

In [ ]:
print(len(result))
display(result)

13

shape: (13, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name       ┆ popularit ┆ null_resp ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---        ┆ y         ┆ onse      ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 2y8kMVtqP1 ┆ Boom Boom  ┆ 0         ┆ 0         ┆ … ┆ 0.00029   ┆ 0.753     ┆ 0.103    ┆ 0.84    │
│ 0nSguUT384 ┆ (Instrumen ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ fC         ┆ tal)       ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 20bsmr6r7Z ┆ Las cosas  ┆ 0         ┆ 0         ┆ … ┆ 0.000284  ┆ 0.774     ┆ 0.127    ┆ 0.838   │
│ CyFuSG00yQ ┆ que hace - ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ qX         ┆ Version 8… ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 4qV8D077wG ┆ 200 Years  ┆ 0         ┆ 0         ┆ … ┆ 0.000476  ┆ 0.778     ┆ 0.116    ┆ 0.781   │
│ gggig1D9wH ┆ Later      ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ YC         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 24WFeTFFTk ┆ Last       ┆ 0         ┆ 0         ┆ … ┆ 0.000247  ┆ 0.766     ┆ 0.116    ┆ 0.782   │
│ aK7ljDCMpT ┆ Chance     ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ c5         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 2RgF3rQn6O ┆ Stay Tuned ┆ 5         ┆ 0         ┆ … ┆ 0.000543  ┆ 0.732     ┆ 0.1      ┆ 0.76    │
│ S2YF207zmC ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 8X         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …       │
│ 70B4CPzlNK ┆ Tequila    ┆ 0         ┆ 0         ┆ … ┆ 0.000598  ┆ 0.72      ┆ 0.093    ┆ 0.83    │
│ a1rWwgmTcZ ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ OY         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 4T1oZ3UAFK ┆ Monolith   ┆ 59        ┆ 0         ┆ … ┆ 0.000409  ┆ 0.756     ┆ 0.114    ┆ 0.799   │
│ braSp5JAIS ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ WW         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 3U0UXxBIfj ┆ Monolith   ┆ 64        ┆ 0         ┆ … ┆ 0.000409  ┆ 0.756     ┆ 0.114    ┆ 0.799   │
│ UsJ8RtxoxU ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ Fn         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 3frkNAvvsC ┆ Twisterell ┆ 6         ┆ 0         ┆ … ┆ 0.000426  ┆ 0.723     ┆ 0.0973   ┆ 0.756   │
│ 8A0lcOIHIq ┆ a          ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ yt         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 4teKraviwF ┆ Power Reps ┆ 0         ┆ 0         ┆ … ┆ 0.000556  ┆ 0.764     ┆ 0.113    ┆ 0.802   │
│ c9LOwXe6V7 ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ MZ         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘